# Generated by Django 3.1.7 on 2021-12-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
