# Generated by Django 3.1.7 on 2021-12-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
    ]
