# Generated by Django 3.1.7 on 2021-12-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreBloque', models.CharField(max_length= 150)),
                ('url', models.CharField(max_length= 200)),

            ],
            options={
                'db_table': 'servicio',
            },
        ),
    ]
