# Generated by Django 3.1.7 on 2021-12-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0002_delete_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bloqueNombre', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=300)),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
    ]
