# Generated by Django 3.1.7 on 2022-01-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0003_servicio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together={('bloqueNombre', 'url')},
        ),
    ]
