# Generated by Django 3.1.7 on 2022-01-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0005_auto_20220121_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='nombreService',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracioncv',
            name='bloqueService',
            field=models.CharField(default='articulos', max_length=150),
        ),
    ]
