# Generated by Django 3.1.7 on 2022-02-16 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0006_auto_20220126_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncv_personalizado',
            name='nombreBloque',
        ),
    ]
