# Generated by Django 3.1.7 on 2022-02-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0007_remove_configuracioncv_personalizado_nombrebloque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncv',
            name='bloqueService',
        ),
    ]
