# Generated by Django 3.1.7 on 2021-11-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0011_auto_20211125_2121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracioncv_personalizado',
            unique_together={('bloque', 'atributo', 'nombre_cv', 'cedula')},
        ),
    ]
